"""
Report Generator Module
Generates professional investigation reports in multiple formats
"""

import json
import os
from datetime import datetime
from pathlib import Path
from rich.panel import Panel
from utils.logger import Logger
from utils.ascii_art import ASCII_BANNERS


class ReportGenerator:
    """Generate investigation reports in multiple formats"""
    
    def __init__(self, console=None, logger=None):
        self.console = console
        self.logger = logger or Logger()
        self.reports_dir = Path("./reports")
        self.reports_dir.mkdir(exist_ok=True)
    
    def get_banner(self):
        """Return module banner"""
        return ASCII_BANNERS['report_module']
    
    def generate(self, investigation_data: dict, report_format: str = "txt") -> str:
        """
        Generate investigation report
        
        Args:
            investigation_data: Collected investigation data
            report_format: Format (txt, json, html)
        
        Returns:
            Path to generated report file
        """
        try:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            
            if report_format == "json":
                return self._generate_json_report(investigation_data, timestamp)
            elif report_format == "html":
                return self._generate_html_report(investigation_data, timestamp)
            else:  # Default to txt
                return self._generate_txt_report(investigation_data, timestamp)
        
        except Exception as e:
            self.logger.error(f"Report generation error: {str(e)}")
            raise
    
    def _generate_txt_report(self, data: dict, timestamp: str) -> str:
        """Generate plain text report"""
        filename = self.reports_dir / f"jasoos_report_{timestamp}.txt"
        
        report_content = f"""
╔════════════════════════════════════════════════════════════════════════════╗
║                         JASOOS OSINT INVESTIGATION REPORT                  ║
║                        Advanced Intelligence Framework                     ║
╚════════════════════════════════════════════════════════════════════════════╝

Report Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")}
Framework Version: 1.0.0
Developer: Shah-Mir
Project Type: Educational OSINT Framework

IMPORTANT NOTICE:
This report is generated for educational and authorized investigation purposes only.
Unauthorized use is strictly prohibited and may be illegal.

════════════════════════════════════════════════════════════════════════════════

INVESTIGATION SUMMARY
────────────────────────────────────────────────────────────────────────────────

"""
        
        # Add sections based on collected data
        if 'phone' in data:
            report_content += self._format_phone_section(data['phone'])
        
        if 'social' in data:
            report_content += self._format_social_section(data['social'])
        
        if 'username' in data:
            report_content += self._format_username_section(data['username'])
        
        if 'email' in data:
            report_content += self._format_email_section(data['email'])
        
        if 'geo' in data:
            report_content += self._format_geo_section(data['geo'])
        
        if 'breach' in data:
            report_content += self._format_breach_section(data['breach'])
        
        # Add footer
        report_content += f"""

════════════════════════════════════════════════════════════════════════════════

REPORT FOOTER
────────────────────────────────────────────────────────────────────────────────

Report ID: {timestamp}
Status: Completed
Confidence Level: Based on public data sources

LEGAL DISCLAIMER:
This report is provided strictly for educational and authorized cybersecurity
investigation purposes. The author assumes no liability for unauthorized use.
All findings should be verified through official channels before taking action.

RECOMMENDATIONS:
1. Verify findings through multiple independent sources
2. Consult with legal authorities if needed
3. Follow all applicable laws and regulations
4. Document chain of custody for evidence
5. Use findings responsibly and ethically

════════════════════════════════════════════════════════════════════════════════

Generated by: Jasoos By Shah-Mir OSINT Framework
Educational Use Only | Final Year Project
════════════════════════════════════════════════════════════════════════════════
"""
        
        with open(filename, 'w') as f:
            f.write(report_content)
        
        self.logger.success(f"Text report generated: {filename}")
        return str(filename)
    
    def _generate_json_report(self, data: dict, timestamp: str) -> str:
        """Generate JSON report"""
        filename = self.reports_dir / f"jasoos_report_{timestamp}.json"
        
        report_data = {
            'metadata': {
                'generated': datetime.now().isoformat(),
                'framework': 'Jasoos By Shah-Mir',
                'version': '1.0.0',
                'developer': 'Shah-Mir',
                'purpose': 'Educational OSINT Investigation'
            },
            'investigation_data': data,
            'legal_notice': 'Educational use only. Unauthorized use is prohibited.',
            'report_id': timestamp
        }
        
        with open(filename, 'w') as f:
            json.dump(report_data, f, indent=2)
        
        self.logger.success(f"JSON report generated: {filename}")
        return str(filename)
    
    def _generate_html_report(self, data: dict, timestamp: str) -> str:
        """Generate HTML report"""
        filename = self.reports_dir / f"jasoos_report_{timestamp}.html"
        
        html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jasoos OSINT Investigation Report</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: 'Courier New', monospace;
            background: #0a0e27;
            color: #00ff00;
            line-height: 1.6;
            padding: 20px;
        }}
        
        .container {{
            max-width: 1000px;
            margin: 0 auto;
            background: #0f1419;
            border: 2px solid #00ff00;
            padding: 30px;
            border-radius: 5px;
        }}
        
        header {{
            text-align: center;
            border-bottom: 2px solid #00ff00;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}
        
        header h1 {{
            font-size: 28px;
            color: #00ff00;
            text-shadow: 0 0 10px #00ff00;
            margin-bottom: 10px;
        }}
        
        header p {{
            color: #00aa00;
            font-size: 12px;
        }}
        
        .section {{
            margin-bottom: 30px;
            padding: 15px;
            border-left: 3px solid #00ff00;
            background: rgba(0, 255, 0, 0.05);
        }}
        
        .section h2 {{
            color: #00ff00;
            margin-bottom: 15px;
            font-size: 18px;
        }}
        
        .info-row {{
            display: flex;
            margin-bottom: 10px;
            padding: 8px;
            background: rgba(0, 255, 0, 0.02);
        }}
        
        .info-label {{
            color: #00ff00;
            font-weight: bold;
            width: 200px;
        }}
        
        .info-value {{
            color: #00aa00;
            flex: 1;
            word-break: break-all;
        }}
        
        .warning {{
            background: rgba(255, 165, 0, 0.1);
            border-left: 3px solid #ffa500;
            padding: 15px;
            margin: 20px 0;
            color: #ffa500;
        }}
        
        .footer {{
            border-top: 2px solid #00ff00;
            padding-top: 20px;
            margin-top: 30px;
            text-align: center;
            color: #00aa00;
            font-size: 12px;
        }}
        
        .timestamp {{
            color: #00ff00;
            font-size: 12px;
            margin-top: 10px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>JASOOS OSINT INVESTIGATION REPORT</h1>
            <p>Advanced Cybersecurity Intelligence Framework</p>
            <p>Educational Use Only | Final Year Project</p>
        </header>
        
        <div class="warning">
            <strong>⚠️  LEGAL NOTICE:</strong> This report is for educational and authorized
            investigations only. Unauthorized use is strictly prohibited.
        </div>
        
        <div class="section">
            <h2>Report Metadata</h2>
            <div class="info-row">
                <div class="info-label">Generated:</div>
                <div class="info-value">{datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Framework:</div>
                <div class="info-value">Jasoos By Shah-Mir v1.0.0</div>
            </div>
            <div class="info-row">
                <div class="info-label">Purpose:</div>
                <div class="info-value">Educational OSINT Investigation</div>
            </div>
        </div>
        
        <div class="section">
            <h2>Investigation Data Summary</h2>
            <div class="info-row">
                <div class="info-label">Total Investigations:</div>
                <div class="info-value">{len(data)} modules executed</div>
            </div>
            <div class="info-row">
                <div class="info-label">Report ID:</div>
                <div class="info-value">{timestamp}</div>
            </div>
        </div>
        
        <div class="warning">
            <strong>DISCLAIMER:</strong> All findings should be verified through official
            channels before taking any action. This framework is provided strictly for
            educational purposes.
        </div>
        
        <div class="footer">
            <p>Generated by: Jasoos By Shah-Mir OSINT Framework</p>
            <p>Developer: Shah-Mir | Final Year Project</p>
            <p class="timestamp">{datetime.now().isoformat()}</p>
        </div>
    </div>
</body>
</html>
"""
        
        with open(filename, 'w') as f:
            f.write(html_content)
        
        self.logger.success(f"HTML report generated: {filename}")
        return str(filename)
    
    def _format_phone_section(self, data) -> str:
        """Format phone intelligence section"""
        return "\nPHONE INTELLIGENCE:\n" + "─" * 80 + "\n\n"
    
    def _format_social_section(self, data) -> str:
        """Format social media section"""
        return "\nSOCIAL MEDIA ENUMERATION:\n" + "─" * 80 + "\n\n"
    
    def _format_username_section(self, data) -> str:
        """Format username reconnaissance section"""
        return "\nUSERNAME RECONNAISSANCE:\n" + "─" * 80 + "\n\n"
    
    def _format_email_section(self, data) -> str:
        """Format email intelligence section"""
        return "\nEMAIL INTELLIGENCE:\n" + "─" * 80 + "\n\n"
    
    def _format_geo_section(self, data) -> str:
        """Format geo metadata section"""
        return "\nGEO METADATA:\n" + "─" * 80 + "\n\n"
    
    def _format_breach_section(self, data) -> str:
        """Format breach check section"""
        return "\nBREACH CHECK:\n" + "─" * 80 + "\n\n"
